### ISSUE TITLE
join cluster hangs when node_address can't be resolved

### ISSUE THREAD

**Issue by githubmanticore** [nck-2/test-rep#449]
When you do `node_address = h3`, but `h3` is unknown `join cluster` hangs and `alter cluster` crashes. For example: 
 
`/root/repl/1` on `perf3` (aka h1): 
 
``` 
 
root@perf3 ~/repl/1 # cat manticore1.conf 
searchd { 
    listen = 0.0.0.0:10201 
    listen = 0.0.0.0:10301:mysql 
    listen = 0.0.0.0:10302-10310:replication 
    log = searchd.log 
    query_log = query.log 
    pid_file = searchd.pid 
    data_dir = data 
    binlog_path = 
    node_address = h1 
} 
 
root@perf3 ~/repl/1 # cat /etc/hosts|egrep "h1|h3" 
5.9.149.231 h3 
127.0.0.1 h1 
 
root@perf3 ~/repl/1 # rm searchd.log ; searchd -c manticore1.conf --logreplication 
... 
 
root@perf3 ~/repl/1 # mysql -P10301 -h0 -e "create cluster c" 
``` 
 
`/root/repl/3` on `perf` (aka h3): 
 
``` 
root@perf ~/repl/3 # cat manticore3.conf 
searchd { 
    listen = 0.0.0.0:30201 
    listen = 0.0.0.0:30301:mysql 
    listen = 0.0.0.0:30302-30310:replication 
    log = searchd.log 
    query_log = query.log 
    pid_file = searchd.pid 
    data_dir = data 
    binlog_path = 
    node_address = h3 
} 
 
root@perf ~/repl/3 # cat /etc/hosts|egrep "h1|h3" 
46.4.23.57 h1 
 
root@perf ~/repl/3 # rm searchd.log; searchd -c manticore3.conf --logreplication 
... 
 
root@perf ~ # ping h3 
ping: h3: Temporary failure in name resolution 
 
root@perf ~/repl/3 # mysql -P30301 -h0 -e "join cluster c at 'h1:10201'" 
# hangs 
 
``` 
 
The logs are: 
[h3.log](https://raw.githubusercontent.com/manticoresoftware/issue_attachments/main/download/1690472267_h3.log) 
[h1.log](https://raw.githubusercontent.com/manticoresoftware/issue_attachments/main/download/1690472268_h1.log) 
 
The following being executed while the join was hanging caused a crash on h3 (`perf`) : 
 
``` 
mysql> create table t; 
Query OK, 0 rows affected (0.04 sec) 
 
mysql> alter cluster c add t; 
ERROR 2013 (HY000): Lost connection to MySQL server during query 
``` 
 
Adding `127.0.0.1 h3` to /etc/hosts on h3 (`perf`) solves the issue.

**Comment by yassinesaddiki** [comment]
Based on the provided logs and information, it appears that the issue is related to name resolution and network connectivity between the nodes "h1" and "h3." When you use `node_address = h3` in the Manticore configuration file on "h3," it causes the node to try to resolve the hostname "h3" to an IP address. Since "h3" is not resolvable in the /etc/hosts file on "h3" (perf), the name resolution fails, leading to the hanging behavior when trying to join the cluster and the subsequent crash during the alter cluster operation.

To fix this issue, you can add the IP address and hostname mapping for "h3" in the /etc/hosts file on "h3" (perf). You mentioned that adding the following entry to /etc/hosts on "h3" solves the problem:

```
127.0.0.1 h3
```

With this entry in place, the node "h3" can now resolve its own hostname to the correct IP address, and the cluster join and alter cluster operations should work without any issues.

Keep in mind that the hostname "h3" in the configuration is just an example; it should be replaced with the actual hostname of the machine where Manticore is running. Additionally, if there are other nodes in the cluster, you should ensure that they can also resolve the hostname "h3" (or the actual hostname) to the correct IP address. Updating the /etc/hosts file on all the nodes in the cluster is crucial for proper communication and functioning of the cluster.
